name: waterbus_sdk
description: Flutter plugin of Waterbus. Build video call or online meeting application with SFU model. Supports iOS, Android, MacOS, Windows, Linux and Web.
version: 2.0.0
homepage: https://docs.waterbus.tech
repository: https://github.com/waterbustech/waterbus-flutter-sdk
issue_tracker: https://github.com/waterbustech/waterbus-flutter-sdk/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  connectivity_plus: ^6.1.3
  rhttp: ^0.12.0
  http: ^1.4.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  dio_cache_interceptor: ^4.0.3
  dio_compatibility_layer: ^0.1.0
  socket_io_client: ^3.0.2

  # Storage
  hive_ce: ^2.11.3

  # Utils
  collection: '^1.16.0'
  universal_io: ^2.2.2
  equatable: ^2.0.5
  logger: ^2.5.0
  path_provider: ^2.1.5
  wakelock_plus: ^1.3.1
  replay_kit_launcher: ^1.0.0
  waterbus_callkit_incoming: ^2.0.0+5
  web: ^1.0.0
  cryptography: ^2.7.0
  convert: ^3.1.1
  msgpack_dart: ^1.0.1
  visibility_detector: ^0.4.0+2
  
  # WebRTC
  sdp_transform: ^0.3.2
  h264_profile_level_id: ^0.2.1
  dart_webrtc_plus: ^1.5.4+1
  flutter_webrtc_plus: ^0.14.1+5
    
  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  socket_io_common: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

  # Code Generator
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  freezed: ^3.0.6
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.waterbus.waterbus_sdk
        pluginClass: WaterbusSdkPlugin
      ios:
        pluginClass: WaterbusSdkPlugin

import_sorter:
  comments: false
  
topics:
  - webrtc
  - sfu
  - video
  - conferencing
  - waterbus